#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# 
# check_informix - check_mk plugin to monitor IBM Informix databases
# Copyright (c) 2012 FuH Entwicklungsgesellschaft mbH, Umkirch, Germany. All rights reserved.
# Author: Philipp Hoefflin, 2012, hoefflin+cmk@fuh-e.de
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation in version 2.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 675 Mass Ave, Cambridge MA 02139, USA or see <http://www.gnu.org/licenses/>
#
# Example output from agent:
# <<<informix_sessions>>>
# ids_shm SESSIONS|22|

# Default thresholds
# ("<Warning max entries>", "<Critical num entries>")
informix_sessions_default_levels = (50, 100)

def inventory_informix_sessions(info):
    return [ (line[0], "informix_sessions_default_levels") for line in info ]

def check_informix_sessions(item, params, info):
    sessions = -1
    warn, crit = params
    for line in info:
        if line[0] == item:
            values = (' '.join(line[1:])).split('|')
            if str(values[0]) == 'SESSIONS':
                if sessions < 0:
                    sessions = 0
                sessions += int(values[1])

    infotext = " - %d active sessions (levels at %d/%d)" % (sessions, warn, crit )
    perfdata = [("sessions", sessions, warn, crit)]
    if sessions == -1:
        return (3, "UNKNOWN" + " - session list not available" )
    elif sessions > crit:
        return (2, "CRIT" + infotext, perfdata)
    elif sessions > warn:
        return (1, "WARN" + infotext, perfdata)
    else:
        return (0, "OK" + infotext, perfdata)

check_info['informix_sessions'] = (check_informix_sessions, "IDS %s sessions", 1, inventory_informix_sessions)
# vim: tabstop=4 shiftwidth=4 expandtab
