#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# 
# check_mk plugin to monitor storage systems like Fujitsu ETERNUS DX80 S2 supporting FJDARY-E100.MIB
# Copyright (c) 2012 FuH Entwicklungsgesellschaft mbH, Umkirch, Germany. All rights reserved.
# Author: Philipp Hoefflin, 2012, hoefflin+cmk@fuh-e.de
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation in version 2.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 675 Mass Ave, Cambridge MA 02139, USA or see <http://www.gnu.org/licenses/>
#
# example snmpwalk output:
# snmpwalk -c public -v 1 dx80 .1.3.6.1.4.1.211.1.21.1.100.2.10.2.1.1
# FJDARY-E100::fjdaryCeIndex.0 = INTEGER: 0
# snmpwalk -c public -v 1 dx80 .1.3.6.1.4.1.211.1.21.1.100.2.10.2.1.3
# FJDARY-E100::fjdaryCeStatus.0 = INTEGER: normal(1)

fjdarye100_hwstatus = { 1: 'normal',  2: 'alarm',       3: 'warning',
                       4: 'invalid', 5: 'maintenance', 6: 'undefined' }

def inventory_fjdarye100(info):
    return [ (int(index), '', None) for index, status in info if int(status) != 4 ]


def check_fjdarye100(index, _no_param, info):
    for line in info:
        if int(line[0]) == index:
            status = int(line[1])

            if status == 1:
                code = 0
            elif status == 3:
                code = 1
            else:
                code = 2

            return (code, '%s - Status is %s' % (nagios_state_names[code], fjdarye100_hwstatus[status]))

    return (3, "UNKNOWN - No status for item %d present" % index)

check_info['fjdarye100_conencs'] = (check_fjdarye100, "Controller Enclosure %s", 0,  inventory_fjdarye100)
# 1: fjdaryCeIndex, 3: fjdaryCeStatus
snmp_info['fjdarye100_conencs'] = (".1.3.6.1.4.1.211.1.21.1.100.2.10.2.1", [ 1, 3 ])

snmp_scan_functions['fjdarye100_conencs'] \
        = lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.211.1.21.1.100"
